# Generated by Django 5.0.4 on 2024-04-12 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('transactions', '0002_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='transactions.category'),
        ),
    ]
