# Generated by Django 5.0.4 on 2024-04-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(null=True, upload_to='media/transactions'),
        ),
    ]
