# Generated by Django 5.0.4 on 2024-04-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_profile_id_alter_profile_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='temp_id',
            new_name='id',
        ),
    ]
